algoritmo "Menu"
var
   Um, Dois, Tres: inteiro
inicio
      Um <- 1
      Dois <- 10
     repita
      Escreval(" |    MENU       | " )
      Escreval(" |               | " )
      Escreval(" | [1] de 1 a 10 | " )
      leia (Um)
      Escreval(" | [2] de 10 a 1 | " )
      leia (Dois)
      Escreval(" | [3] Sair      | " )
      leia (Tres)
      Um <- Um + 1
      (1 = 10)
      Dois <- 2 - 1
      ate (10 = 1)

fimalgoritmo